# Generated by Django 4.1.1 on 2022-09-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('year', models.SmallIntegerField(default=1990)),
                ('released', models.BooleanField(default=False)),
            ],
        ),
    ]
