# Generated by Django 4.1.1 on 2022-09-23 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_movie_description_movie_imdb_rating_movie_premiere'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(default=120)),
                ('genre', models.IntegerField(choices=[(0, 'Horror'), (1, 'Comedy'), (2, 'Action'), (3, 'Drama'), (4, 'Other')], default=4)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='additional_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.additionalinfo'),
        ),
    ]
